### ISSUE TITLE
Moving this into backend ?

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-emails#20]
I guess it would make more sense to move this whole thing into the backend?
We can setup a sample app to render the emails and perform whole inline-css stuff.

One big advanatage is we can actually make use of templating system in the backend with the same syntax etc

**Comment by AmirSavand** [comment]
@Alir3z4 yes, once the backend can support a base template, we could.

**Comment by Alir3z4** [comment]
Hmmm

Yeah we can.
We only need to apply 1 more rendering part when syncing the templates and
then it would be just fine.

**Comment by AmirSavand** [comment]
@Alir3z4 yes, the emails should be generated, not rendered every time we send an email.
