### ISSUE TITLE
Use blocktrans instead of trans when necessary 

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-emails#8]
in file `comment_notification_participates.html`
```
<h1>{{ user_name }} {% trans 'responded to "{{ object_title }}"' %}</h1>
```

should use `blocktrans`

This is broken by now

**Comment by Alir3z4** [comment]
@AmirSavand @ArsalanSavand This is urgent and needs to be fixed very soon,

**Comment by AmirSavand** [comment]
@Alir3z4 Is this fine?
```
<h1>{% blocktrans %}{{ user_name }} responded to "{{ object_title }}"{% endblocktrans %}</h1>
```

**Comment by Alir3z4** [comment]
Yes, it works good ;)
I'll merge and run the tests and re-open the issue if anything happened
